### ISSUE TITLE
Unable to update to 1.0.42

### ISSUE THREAD

**Issue by MaikKlein** [EmbarkStudios/ash-molten#19]
Two issues

- [x] Github actions doesn't have the latest version of xcode 11.5

- [ ] On `OSX 10.15.4` and `xcode 11.5` I get an unknown symbol in moltenvk `___isPlatformVersionAtLeast`. I am not sure where it is coming from. 

    After scavenging a few forum it appears to be defined in `compiler-rt` which is supposed to be re-exported by `libSystem`. But that is not the case on my system.

**Comment by repi** [comment]
As I mentioned on Slack, GitHub Actions does have support for Xcode 11.5 so that is just a simple change in the `ci.yaml` here.

https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md

**Comment by repi** [comment]
Closing as we managed to move to latest 1.1.0 release instead in #25 today
