### ISSUE TITLE
Prebuilt binary support for aarch64-apple-darwin

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/ash-molten#36]
Currently the Vulkan SDK doesn't include a pre-built MoltenVK library for the `aarch64-apple-darwin` target so we haven't uploaded it here for use with the `pre-built` feature. But we will want to have that fairly soon, either from a new Vulkan SDK (ideally) or build it ourselves. 

In the meantime one will have to build MoltenVK from source and not use the `pre-built` feature

**Comment by VZout** [comment]
We support this :)
