### ISSUE TITLE
Upgrade to MoltenVK v1.1.5

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/ash-molten#60]
Looks like it contains quite a few Apple M1 fixes as well as new SPIRV-Cross version which is good. cc @VZout @hrydgard 

https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.1.5

**Comment by hrydgard** [comment]
Oh!

```Vulkan timestamp query pools use Metal GPU counters when available```

Maybe we can get the GPU profiler working!

**Comment by repi** [comment]
That would be great!
