### ISSUE TITLE
Is it intended that the (library) build succeeds on non-macOS/iOS?

### ISSUE THREAD

**Issue by eddyb** [EmbarkStudios/ash-molten#70]
https://github.com/EmbarkStudios/ash-molten/blob/09bed931f0e138707e5e1b39d4e54092350715af/build/build.rs#L375-L378

That build script will just print a message that will never be forwarded to the user, because it also "succeeds" (since it doesn't panic, nor exit with a non-0 return code - either via `fn main() -> ...` or `std::process::exit`).

Is this intentional? `cargo run`, and many other uses of the library, will still fail with a linker error.

**Comment by MarijnS95** [comment]
I suggested to do the same in https://github.com/EmbarkStudios/ash-molten/pull/56#issuecomment-877034275, or even replace it with `println!("cargo:rustc-link-lib=vulkan");` to be able to build-test this crate on non-Mac (even though that's trivial and part of core `ash` now).

**Comment by eddyb** [comment]
Heh, this "bug"(?) made testing my PR (#71) easier, and I could see the appeal.
We could maybe at least [emit a `cargo:warning=`](https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargo-warning) with a message like "this crate doesn't do anything outside of macOS/iOS".

Oh but Cargo isn't printing those for dependencies by default. Maybe the exported function could just panic at runtime?
