### ISSUE TITLE
Disable MoltenVK compilation for Clippy/RLS/tests

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/ash-molten#9]
@MaikKlein would it be possible to disable compiling the full C++ MoltenVK dependency when building with clippy, tests and for RLS? 

As it can take 5+ min to compile MoltenVK on a MBP15 it would be nice to not have to build it for configurations where it is not used in practice.

**Comment by MaikKlein** [comment]
I don't think this is possible. I don't think clippy and rls add a specific feature flag that one can check for. 

But users really should just sepcify `--feature external` and link with a prebuilt lib, then everything would be fast.

**Comment by repi** [comment]
> I don't think this is possible. I don't think clippy and rls add a specific feature flag that one can check for.

I do think this is possible, at least for some of the configs and a bit hacky. Believe I've seen it in some other crate 

> But users really should just sepcify --feature external and link with a prebuilt lib, then everything would be fast.

That is not a valid answer, requires users and all of our devs to manually build the right matching version separately and then modify this. That is not how we use this crate.

**Comment by repi** [comment]
We almost exclusively used MoltenVK pre-compiled since quite a while back so this is less of an issue for us
